# Generated by Django 3.0.5 on 2020-04-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DUT_IP', models.GenericIPAddressField()),
                ('HDT_IP', models.GenericIPAddressField(blank=True, null=True)),
                ('user_name', models.SlugField(blank=True, max_length=100, null=True)),
                ('host_name', models.SlugField(help_text='a uniq name for your dut', max_length=100)),
                ('password', models.SlugField(blank=True, max_length=100, null=True)),
                ('tag', models.SlugField(blank=True, help_text='For example: John_3dmark_11_12', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='email address', max_length=100, null=True, verbose_name='email_address')),
                ('status', models.SmallIntegerField(choices=[(0, 'Online'), (1, 'Offline'), (2, 'Unknow'), (3, 'Busy')], default=0, verbose_name='device status')),
                ('Owner', models.SlugField(default='Admin', max_length=100)),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
            ],
            options={
                'verbose_name': 'Devices',
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('Owner', models.SlugField(default='Admin', max_length=100)),
                ('tag', models.SlugField(blank=True, help_text='For example: John_3dmark_11_12', max_length=100, null=True)),
                ('status', models.SlugField(default='UNKNOWN', max_length=100)),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
            ],
        ),
    ]
