# Generated by Django 2.2.7 on 2019-11-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DUT_IP', models.GenericIPAddressField()),
                ('HDT_IP', models.GenericIPAddressField()),
                ('user_name', models.SlugField()),
                ('password', models.SlugField()),
                ('tag', models.SlugField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='email address', max_length=100, null=True, verbose_name='email_address')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
