# Generated by Django 2.2 on 2019-11-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DUT_IP', models.GenericIPAddressField()),
                ('HDT_IP', models.GenericIPAddressField(blank=True, null=True)),
                ('user_name', models.SlugField(blank=True, max_length=100, null=True)),
                ('host_name', models.SlugField(help_text='a uniq name for your dut', max_length=100, unique=True)),
                ('password', models.SlugField(blank=True, max_length=100, null=True)),
                ('tag', models.SlugField(blank=True, help_text='For example: John_3dmark_11_12', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='email address', max_length=100, null=True, verbose_name='email_address')),
                ('status', models.SmallIntegerField(choices=[(0, 'online'), (1, 'offline'), (2, 'unknow'), (3, 'busy')], default=0, verbose_name='device status')),
                ('Owner', models.SlugField(default='Admin', max_length=100)),
                ('m_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
            ],
            options={
                'verbose_name': 'Devices',
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Users',
                'verbose_name_plural': 'Users',
                'ordering': ['-c_time'],
            },
        ),
    ]
