# Generated by Django 2.2.7 on 2019-11-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydevice',
            name='host_name',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mydevice',
            name='HDT_IP',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mydevice',
            name='password',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mydevice',
            name='tag',
            field=models.SlugField(blank=True, help_text='For example: Xiaoming_3dmark_11_12', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mydevice',
            name='user_name',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
