# Generated by Django 2.2 on 2019-10-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DUT_IP', models.GenericIPAddressField()),
                ('HDT_IP', models.GenericIPAddressField()),
                ('user_name', models.SlugField()),
                ('password', models.SlugField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
