# Generated by Django 2.2.7 on 2019-12-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_auto_20191129_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Owner',
            field=models.SlugField(default='Admin', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='m_time',
            field=models.DateTimeField(auto_now=True, verbose_name='update time'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'PASS'), (1, 'FAIL'), (2, 'RUNNING'), (3, 'PAUSE')], default=0, verbose_name='task status'),
        ),
        migrations.AlterField(
            model_name='mydevice',
            name='host_name',
            field=models.SlugField(help_text='a uniq name for your dut', max_length=100),
        ),
    ]
