# Generated by Django 2.2 on 2019-11-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydevice',
            name='tag',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mydevice',
            name='email',
            field=models.EmailField(blank=True, help_text='email address', max_length=100, null=True, verbose_name='email_address'),
        ),
    ]
