# Generated by Django 2.2.7 on 2019-12-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_auto_20191211_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
