# Generated by Django 2.2.7 on 2019-12-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_task_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comments',
            field=models.SlugField(blank=True, help_text='For example: John_3dmark_11_12', max_length=100, null=True),
        ),
    ]
