# Generated by Django 2.2.7 on 2019-12-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0007_auto_20191212_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='comments',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'PASS'), (1, 'FAIL'), (2, 'RUNNING'), (3, 'PAUSE'), (4, 'NEW')], default=0, verbose_name='task status'),
        ),
    ]
